apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jobber
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: printer=ghcr.io/markthequark/printer
    argocd-image-updater.argoproj.io/printer.force-update: "true"
    argocd-image-updater.argoproj.io/printer.update-strategy: latest
    argocd-image-updater.argoproj.io/printer.pull-secret: pullsecret:argocd/dockerconfigjson-github-com
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/markthequark/argocd.git
    targetRevision: HEAD
    path: helm_charts/configmap
    helm:
      values: |
        name: my-configmap
        image:
          name: ghcr.io/markthequark/printer
          tag: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
